name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run release-drafter
        run: npx release-drafter --config .github/release-drafter.yml --token ${{ secrets.GITHUB_TOKEN }}
      - name: Add pull request comment
        uses: peter-evans/add-pull-request-comment@v1
        with:
          message: "Release drafter has updated the release draft."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
