name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install Release Drafter
        run: npm install -g release-drafter@v7

      - name: Get latest tag
        id: latest_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Generate release notes
        id: release_notes
        run: |
          echo "Generating release notes based on commit messages since tag ${{ steps.latest_tag.outputs.tag }}..."
          release-drafter --config .github/release-drafter.yml \
                          --token ${{ secrets.GITHUB_TOKEN }} \
                          --latest-tag ${{ steps.latest_tag.outputs.tag }}

      - name: Update release draft
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: Update release notes
          branch: release-drafter-${{ github.sha }}
          title: Update release notes
          body: |
            This is an automated pull request to update the release notes based on the commit messages since the latest tag.
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
