name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get previous release tag
        run: |
          git fetch --tags
          echo "::set-output name=prev_tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
        id: prev_tag
      - name: Get current release notes
        run: |
          echo "::set-output name=release_notes::$(git log --pretty=format:'- %s' --no-merges ${prev_tag.outputs.prev_tag}..HEAD)"
        id: release_notes
      - name: Update Release Notes
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-config.yml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Release Notes to Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            const prNumber = context.payload.pull_request.number;
            const notes = ${{ toJSON(steps.release_notes.outputs.release_notes) }};
            github.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: `Release Notes:\n${notes}`
            });
