name: Update Release Draft on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Release Notes
        run: npx standard-version

      - name: Get Latest Release Tag
        id: latest_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_RELEASE_TAG: ${{ steps.latest_tag.outputs.tag }}

      - name: Add PR comment
        uses: peter-evans/add-pull-request-comment@v1.1.1
        with:
          message: 'Release draft updated with new commit. :tada:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
