name: Update Release Draft

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update release draft
        run: |
          last_release=$(git describe --tags --abbrev=0)
          release_name=$(git log --format="%s" $last_release.. | tr '\n' ';')
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"name":"'"$last_release"'", "tag_name":"'"$last_release"'", "body":"'"$release_name"'"}' \
            -X PATCH \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$last_release"
