name: Update Release Draft

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install necessary actions
    - name: Install actions
      run: |
        git clone https://github.com/peter-evans/add-pull-request-comment.git
        git clone https://github.com/release-drafter/release-drafter.git

    # Update release draft
    - name: Update release draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
        DRAFT_VERSION: ${{ github.ref_name }}
      with:
        config-name: .github/release-drafter.yml

    # Add comment to pull request
    - name: Add comment to pull request
      uses: peter-evans/add-pull-request-comment@v1
      with:
        message: |
          Release draft has been updated.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
